services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file:
      - ./apps/backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/portfolio_db
    volumes:
      - ./apps/backend:/app
    command: sh -c "npm install && npm run start:dev"

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./apps/frontend:/app
    command: sh -c "npm install && npm run dev"

  ticker-updater:
    build:
      context: .
      dockerfile: apps/ticker-updater/Dockerfile
    env_file:
      - ./apps/ticker-updater/.env
    depends_on:
      - postgres
    volumes:
      - ./apps/ticker-updater:/app
    command: sh -c "npm install && npm run start"

volumes:
  postgres-data:
