name: Frontend CI

on:
  workflow_dispatch:
  workflow_call:
#  push:
#    paths:
#      - 'apps/frontend/**'
#      - 'package-lock.json'

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install root dependencies
        run: npm ci

      - name: Build and Test
        run: |
          cd apps/frontend
          npm run build
          npm test || echo "No tests yet"
